

sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

title: "DigilinkDrenthe" # the name of your site, e.g. ACME Corp.
tagline: "Digitalize the world"
email: "info@digilinkdrenthe.nl"
description: >- # this means to ignore newlines until "baseurl:"
author: DigilinkDrenthe
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/digilinkdrenthe.netlify.app" # the subpath of your site, e.g. /blog
google_analytics: UA-111111111-1
twitter:
  username: 
  card: summary #keep this to generate a twitter share card
