backend:
  name: github
  repo: spronchev/jekyll-starter
media_folder: '_site/assets/img'
collections:
  - name: 'pages'
    label: 'Pages'
    files:
    - label: "Home page"
      name: "homepage"
      file: "_site/_data/homepage.yml"
      fields:
        - label: "Header section"
          name: "header"
          widget: "object"
          fields:
            - label: "Title"
              name: "title"
              widget: "string"

