site_url: http://localhost:4000
backend:
  name: github
  repo: spronchev/jekyll-starter
  branch: main

media_folder: '/assets/img'
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "_data/homepage.yml"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title Header One, name: title_first, widget: string}
          - {label: Title Header Two, name: title_second, widget: string}
          - {label: Sub Title, name: title_sub, widget: string}
          - {label: Button Text, name: text_button, widget: string}
          - {label: Description, name: text_description, widget: text}
          - {label: Description Sub Text One, name: text_description_first, widget: string}
          - {label: Description Sub Text Two, name: text_description_second, widget: string}
          - label: "Images with text and button"
            name: "image_text_button"
            widget: "object"
            collapsed: true
            fields:
              - label: "Box One"
                name: "box_one"
                widget: "object"
                collapsed: true
                fields:
                  - {label: Featured Image, name: box_one_image_first, widget: image, choose_url: true, default: "/assets/img/shutterstock_508654513.jpg"}
                  - {label: Title One, name: box_one_title_first, widget: string}
                  - {label: Title Two, name: box_one_title_second, widget: string}
                  - {label: Description Text, name: box_one_text_description, widget: text}
                  - {label: Button Text, name: box_one_text_button, widget: string}
              - label: "Box Two"
                name: "box_two"
                widget: "object"
                collapsed: true
                fields:
                  - {label: Featured Image, name: box_two_image_first, widget: image, choose_url: true, default: "/assets/img/shutterstock_508654513.jpg"}
                  - {label: Title One, name: box_two_title_first, widget: string}
                  - {label: Title Two, name: box_two_title_second, widget: string}
                  - {label: Description Text, name: box_two_text_description, widget: text}
                  - {label: Button Text, name: box_two_text_button, widget: string}
              - label: "Box Three"
                name: "box_three"
                widget: "object"
                collapsed: true
                fields:
                  - {label: Featured Image, name: box_three_image_first, widget: image, choose_url: true, default: "/assets/img/shutterstock_508654513.jpg"}
                  - {label: Title One, name: box_three_title_first, widget: string}
                  - {label: Title Two, name: box_three_title_second, widget: string}
                  - {label: Description Text, name: box_three_text_description, widget: text}
                  - {label: Button Text, name: box_three_text_button, widget: string}
              - label: "Box Four"
                name: "box_four"
                widget: "object"
                collapsed: true
                fields:
                  - {label: Featured Image, name: box_four_image_first, widget: image, choose_url: true, default: "/assets/img/shutterstock_508654513.jpg"}
                  - {label: Title, name: box_four_title_first, widget: string}
                  - {label: Sub Title, name: box_four_title_second, widget: string}
                  - {label: Description, name: box_four_text_description, widget: text}
                  - {label: Button Text, name: box_four_text_button, widget: string}
          - label: "Sub main body"
            name: "sub_main"
            widget: "object"
            collapsed: true 
            fields:
                - {label: Sub Main Title, name: sub_main_title, widget: string}
                - label: "Sub Main Description"
                  name: "sub_main_first"
                  widget: "object"
                  collapsed: true
                  fields:
                    - {label: Image, name: sub_main_image_first, widget: image, choose_url: true, default: "/assets/img/shutterstock_508654513.jpg"}
                    - {label: Title, name: sub_main_title_first, widget: string}
                    - {label: Description, name: sub_main_text_first, widget: text}
                - label: "Sub Main Description"
                  name: "sub_main_second"
                  widget: "object"
                  collapsed: true
                  fields:
                    - {label: Image, name: sub_main_image_second, widget: image, choose_url: true, default: "/assets/img/shutterstock_508654513.jpg"}
                    - {label: Title, name: sub_main_title_second, widget: string}
                    - {label: Description Text, name: sub_main_text_second, widget: text}
                - label: "Sub Main Description"
                  name: "sub_main_third"
                  widget: "object"
                  collapsed: true
                  fields:
                    - {label: Image, name: sub_main_image_third, widget: image, choose_url: true, default: "/assets/img/shutterstock_508654513.jpg"}
                    - {label: Title, name: sub_main_title_third, widget: string}
                    - {label: Description, name: sub_main_text_third, widget: text}
                - {label: Button Text, name: sub_main_text_button, widget: string}
    

