backend:
  name: github
  repo: spronchev/jekyll-starter
media_folder: 'assets/uploads'
collections:
  - name: 'pages'
    label: 'Pages'
    files:
    - label: "Home page"
      name: "index"
      file: "_data/homepage.yml"
      fields:
        - label: "Header section"
          name: "header"
          widget: "object"
          fields:
            - label: "Title"
              name: "title"
              widget: "string"

