backend:
  name: github
  repo: 'https://github.com/spronchev/jekyll-starter'
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }