backend:
  name: github
  repo: spronchev/jekyll-starter
media_folder: 'assets/img'
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "_data/homepage.yml"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}

